server:
  port: 8082

spring:
  application:
    name: extract-service

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: extract-service-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      properties:
        spring.deserializer.value.delegate.class: org.springframework.kafka.support.serializer.JsonDeserializer
        spring.json.trusted.packages: "*"
      enable-auto-commit: false
  
  data:
    mongodb:
      uri: mongodb://localhost:27017/agibank_extracts
      database: agibank_extracts

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html

logging:
  level:
    br.com.agibank.extract: DEBUG
    org.springframework.data.mongodb: INFO
    org.springframework.kafka: INFO
    root: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
