server:
  port: 8083

spring:
  application:
    name: notifications-service
  
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: notifications-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html

logging:
  level:
    br.com.agibank: DEBUG
